# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-18 19:07
from __future__ import unicode_literals

import MainApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=MainApp.models.user_directory_path)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 3, 19, 0, 37, 52, 67217))),
                ('hits', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, default=None, unique=True)),
                ('writer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
