# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=100),
        ),
    ]
