# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20170226_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 12, 15, 30, 279257)),
        ),
    ]
