# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20170226_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 12, 33, 24, 158686)),
        ),
    ]
