# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 07:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20170226_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 26, 12, 36, 48, 515974)),
        ),
    ]
