# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 15:24
from __future__ import unicode_literals

import MainApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20170226_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=MainApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 5, 20, 54, 34, 262730)),
        ),
    ]
