# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20170305_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 21, 17, 4, 778000)),
        ),
    ]
