# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 18:04
from __future__ import unicode_literals

import MainApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_auto_20170317_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=MainApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 23, 34, 52, 509594)),
        ),
    ]
